# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('sinopse', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=15)),
                ('trailer_url', models.CharField(max_length=200)),
            ],
        ),
    ]
