# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviestrailer',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
